add work and about section
kingsleyocran/mc_portfolio pull request #3
Opened 2022-05-26 19:17 UTC by kingsleyocran

- Add about section to index.html
- Add work section to index.html
- Modified style.css with design and layout requirements of about and work section.
- Add new web assets; images and svgs.

2022-05-26 19:50 UTC, vechicin requested changes
# Hi @kingsleyocran  ✋, 

Good job so far! 🔥 
There are some issues that you still need to work on to go to the next project but you are almost there! 🚨 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights ⚡ 

- [x] Correct GitHub Flow
- [x] Fantastic job following the design template
- [x] Good PR title/description
- [x] Good README
- [x] Highly organized codebase 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 📂 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-26 19:50 UTC, vechicin commented on css/build/style.css
> +}
Great job implementing the hover feature, really smooth transition, looks great! 🎉 
However, you're still missing the `active` interaction. Please add it.

<img width="833" alt="Screen Shot 2022-05-26 at 14 39 29" src="https://user-images.githubusercontent.com/82426682/170564505-ed867852-1e4e-4dd3-a542-2cf6da5ae9bd.png">

2022-05-26 19:50 UTC, vechicin commented on index.html
> +        <p class="head-text-1">LET'S CONNECT</p>
According to the review guidelines, this text should be wrapped inside a `<hx>` tag. Kindly fix this.

<img width="438" alt="Screen Shot 2022-05-26 at 14 42 30" src="https://user-images.githubusercontent.com/82426682/170564991-c83421f9-1c32-4bd0-8813-948d724f3df1.png">

2022-05-26 19:50 UTC, vechicin commented on index.html
> +          <button type="button" class="work-card-button button-text-1">See Project</button>
The comment for the button above applies here as well. Additionally, the text in the template is `Get my resume`, not `See Project`. Kindly fix this.

2022-05-26 19:50 UTC, vechicin commented on index.html
> +            </div>
According to the evaluation guidelines, this section should be wrapped inside `<ul>` and `<li>` tags as well.

<img width="747" alt="Screen Shot 2022-05-26 at 14 46 29" src="https://user-images.githubusercontent.com/82426682/170565618-cc5b50fc-6eac-49b9-a4f5-bbcb5d6fb44e.png">

Kindly fix this.

2022-05-26 19:50 UTC, vechicin commented
https://github.com/kingsleyocran/mc_portfolio/blob/029605fbed7448458b643e5784fa2e9aaa27c037/README.md?plain=1#L16-L18

I recommend you remove this section until you deploy an actual demo.

2022-05-26 19:51 UTC, vechicin commented
https://github.com/kingsleyocran/mc_portfolio/blob/029605fbed7448458b643e5784fa2e9aaa27c037/README.md?plain=1#L4-L6

Please don't forget to add a project name and description.

2022-05-26 19:52 UTC, vechicin commented
https://github.com/kingsleyocran/mc_portfolio/blob/029605fbed7448458b643e5784fa2e9aaa27c037/README.md?plain=1#L46-L50

I suggest you remove these unused headers, it'll keep your documentation clean which is desirable.

2022-05-26 19:53 UTC, vechicin commented
https://github.com/kingsleyocran/mc_portfolio/blob/029605fbed7448458b643e5784fa2e9aaa27c037/README.md?plain=1#L54-L59

Please change `Author` to your full name. It'll give you more visibility. Add your social media handles as opposed to the generic `@githubhandle` or `LinkedIn` tags, it'll make your documentation look more professional.

2022-05-27 07:25 UTC, OLIPLICHE approved these changes
Hi @kingsleyocran , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-27 07:40 UTC, merged